version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: email-assistant-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emaildb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  mysql_data:
